(681,)
(841,)
len(np.shape(lat)) == 1
(681, 841)
(681, 841)
0.049999237
0.05000305
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
[0.0000e+00 3.0000e+01 6.0000e+01 ... 5.2695e+05 5.2698e+05 5.2701e+05]
minutes since 2000-01-01 00:15:00
time
proleptic_gregorian
<class 'netCDF4._netCDF4.Variable'>
float64 time(time)
    units: minutes since 2000-01-01 00:15:00
    long_name: time
    calendar: proleptic_gregorian
unlimited dimensions: 
current shape = (17568,)
filling on, default _FillValue of 9.969209968386869e+36 used
carry on read_cable_var
(179, 199)
(179, 199)
len(np.shape(lat)) == 2
0.0
0.0
17568
(17568, 179, 199)
[]
[]
Traceback (most recent call last):
  File "netCDF4/_netCDF4.pyx", line 4866, in netCDF4._netCDF4.Variable.__setitem__
  File "/g/data/w35/mm3972/anaconda3/envs/science/lib/python3.7/site-packages/numpy/ma/core.py", line 3385, in shape
    super(MaskedArray, type(self)).shape.__set__(self, shape)
ValueError: cannot reshape array of size 0 into shape (17568,1,1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_pixel_met_new_LIS-CABLE.py", line 527, in <module>
    generate_pixel_met(fname_in, fname_out, loc_lat, loc_lon, CO2_val, css_val, cnsd_val, rho_val, org_val, watr_val, lat_name, lon_name)
  File "generate_pixel_met_new_LIS-CABLE.py", line 293, in generate_pixel_met
    SWdown[:,0,0] = swdown
  File "netCDF4/_netCDF4.pyx", line 4868, in netCDF4._netCDF4.Variable.__setitem__
  File "<__array_function__ internals>", line 6, in broadcast_to
  File "/g/data/w35/mm3972/anaconda3/envs/science/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/g/data/w35/mm3972/anaconda3/envs/science/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 127, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (0,) and requested shape (17568,1,1)

======================================================================================
                  Resource Usage on 2021-09-19 11:05:11:
   Job Id:             28679873.gadi-pbs
   Project:            w35
   Exit Status:        1
   Service Units:      3.88
   NCPUs Requested:    1                      NCPUs Used: 1               
                                           CPU Time Used: 00:01:21                                   
   Memory Requested:   256.0GB               Memory Used: 25.63GB         
   Walltime requested: 02:00:00            Walltime Used: 00:06:33        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
